/* after changing this file run 'npm run webpack:build' */
/* tslint:disable */
import '../content/scss/vendor.scss';

// Imports all fontawesome core and solid icons

import { library } from '@fortawesome/fontawesome-svg-core';
import {
    faUser,
    faSort,
    faSortUp,
    faSortDown,
    faSync,
    faEye,
    faBan,
    faTimes,
    faArrowLeft,
    faSave,
    faPlus,
    faPencilAlt,
    faBars,
    faThList,
    faUserPlus,
    faRoad,
    faTachometerAlt,
    faHeart,
    faList,
    faBell,
    faBook,
    faHdd,
    faFlag,
    faWrench,
    faClock,
    faCloud,
    faSignOutAlt,
    faSignInAlt,
    faCalendarAlt,
    faSearch,
    faTrashAlt,
    faAsterisk,
    faTasks,
    faHome,
    faCogs,
    faKey,
    faUserLock,
    faBookOpen,
    faUserCog,
    faCircleNotch,
    faBookmark,
    faClone,
    faCaretDown,
    faCaretLeft,
    faCaretRight,
    faMinusCircle,
    faPlusCircle,
    faCheck,
    faArrowRight,
    faDownload,
    faPen,
    faLink,
    faFolderOpen,
    faThumbtack,
    faDiceD6,
    faChalkboardTeacher,
    faMoneyBillAlt,
    faHandHoldingUsd,
    faCalendar,
    faArrowCircleDown,
    faArrowDown
} from '@fortawesome/free-solid-svg-icons';

// Adds the SVG icon to the library so you can use it in your page
library.add(
    faCalendar,
    faChalkboardTeacher,
    faArrowLeft,
    faTimes,
    faBan,
    faEye,
    faSync,
    faSortDown,
    faSortUp,
    faSort,
    faUser,
    faHeart,
    faTachometerAlt,
    faRoad,
    faUserPlus,
    faThList,
    faHome,
    faBars,
    faPencilAlt,
    faPlus,
    faSave,
    faList,
    faBell,
    faTasks,
    faBook,
    faHdd,
    faFlag,
    faPlusCircle,
    faCheck,
    faArrowRight,
    faDownload,
    faPen,
    faLink,
    faFolderOpen,
    faThumbtack,
    faDiceD6,
    faMinusCircle,
    faCaretRight,
    faCaretLeft,
    faCaretDown,
    faClone,
    faBookmark,
    faCircleNotch,
    faUserCog,
    faBookOpen,
    faUserLock,
    faKey,
    faCogs,
    faAsterisk,
    faTrashAlt,
    faSearch,
    faCalendarAlt,
    faSignInAlt,
    faSignOutAlt,
    faCloud,
    faClock,
    faWrench,
    faMoneyBillAlt,
    faHandHoldingUsd,
    faArrowCircleDown,
    faArrowDown
);

// jhipster-needle-add-element-to-vendor - JHipster will add new menu items here
