version: '2'
services:
    ceteb-app:
        image: mandata
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://mandata-postgresql:5432/mandata
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    ceteb-postgresql:
        extends:
            file: postgresql.yml
            service: mandata-postgresql
